plugin:
    name: 'planetadeleste.jwtauth::lang.plugin.name'
    description: 'planetadeleste.jwtauth::lang.plugin.description'
    author: PlanetaDelEste
    icon: oc-icon-key
    homepage: 'https://github.com/planetadeleste/oc-jwtauth'
